root_dir=/Uploads
http_port=9095
http_user_encript_key=1234598465cjbcds
http_file_upload=false
http_access_file=true
http_debug=true
http_log_file_address=/logs.log
file_size_lim=17000000
file_spli_size=256
VPNPort=8085
VPNTPort=8089
VT600Enc=ZR8Mag$H?k{giJLg}8B0bcJS
ip_address=192.168.1.3